# Generated by Django 3.2.19 on 2023-06-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSala', models.CharField(max_length=100)),
                ('nomeAdmin', models.CharField(max_length=100)),
            ],
        ),
    ]
