# Generated by Django 3.2.19 on 2023-06-27 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salasAPI', '0002_sala_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='data',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
